TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_vel_theta: 0.6
  min_in_place_vel_theta: 0.3
  
  acc_lim_theta: 1.5
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  
  holonomic_robot: false
  
  # Goal tolerance
  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.25
  latch_xy_goal_tolerance: false
  
  # Forward simulation parameters
  sim_time: 2.0
  vx_samples: 10
  vtheta_samples: 20
  
  # Oscillation prevention
  oscillation_reset_dist: 0.05
  
  # Differential drive parameters
  escape_vel: -0.1
  
  # Obstacle avoidance parameters
  avoid_obstacles: 1
