obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]
inflation_radius: 0.55

observation_sources: octomap_cloud

octomap_cloud: {
  sensor_frame: usb_cam, 
  data_type: PointCloud2, 
  topic: /octomap_point_cloud_centers, 
  marking: true, 
  clearing: true,
  min_obstacle_height: 0.1,
  max_obstacle_height: 2.0
}
